spring:
  application:
    name: fitness-management-system

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

server:
  port: ${SERVER_PORT:8080}

  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

  servlet:
    context-path: /


management:

  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: when_authorized


springdoc:

  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html

app:
  initial-admin:
    email: ${ADMIN_EMAIL:admin@fitnesscenter.com}
    password: ${ADMIN_PASSWORD:ChangeMe123!}